version: '3.7'
services:
  front:
    stdin_open: true
    build:
      context: ./polystage-app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - 'app/node_modules'
      - './polystage-app:/app'
    networks:
      - net
  backend:
    build:
      context: ./Node
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - net
    restart: on-failure
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - net

  myadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    networks:
      - net

networks:
  net:
    driver: bridge
