version: '3.7'
services:
    front:
        stdin_open: true
        build: 
            context: ./polystage-app
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes: 
            - "app/node_modules"
            - "./polystage-app:/app"
        networks:
            - net

networks:
    net:
        driver: bridge
