version: '3.7'
services:
  front:
    stdin_open: true
    build:
      context: ./polystage-app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - 'app/node_modules'
      - './polystage-app:/app'
    networks:
      - net
  backend:
    build:
      context: ./Node
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - net
    restart: on-failure
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    image: mysql:5.7
    networks:
      - net
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    networks:
      - net

networks:
  net:
    driver: bridge
