# Create image based on the official Node 10 image from dockerhub
FROM node:latest

# set working directory
WORKDIR /polystage-app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g react

# add app
COPY . ./

# start app
CMD ["npm", "start"]